apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    "service": "true"
    "service-type": "ClusterIP"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.13
        ports:
        - containerPort: 80